version: '3'
services:
  docker-bench-security:
    build: .
    volumes:
      - /var/lib:/var/lib
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/systemd:/usr/lib/systemd
      - /etc:/etc
    stdin_open: true
    tty: true
    cap_add:
      - audit_control
