version: '3'
    # use image if you have a dedicated build step:
    #     #   docker build --rm -t docker-bench-security .
    #         # image: docker-bench-security
    #
    #             # use build path to Dockerfile if docker-compose should build the image
services:
      
  docker-bench-security:
    #image: docker-bench-security
    build: .
    volumes:
      - /var/lib:/var/lib
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/systemd:/usr/lib/systemd
      - /etc:/etc
    stdin_open: true
    tty: true
    cap_add:
      - audit_control
