version: '3'

services:
      
  docker-bench-security:
    #image: docker-bench-security
    build: .
    #container_name: web
    #ports:
    #  - "8899:8000"
    volumes:
      - /var/lib:/var/lib
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/systemd:/usr/lib/systemd
      - /etc:/etc
    stdin_open: true
    tty: true
    cap_add:
      - audit_control
