name: docker bench security action
on: [push]
jobs:
  actions:
    runs-on: ubuntu-latest
    name: A job to check docker bench security issues
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker bench security
        uses: ./ # Uses an action in the root directory
